# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3915197d968020056e0b1f599a29500884eabf81c0b44f02ca6f18659fd34d7cbcdd4657e4088ae8b399864b4000127a0cdaa3930066404eb07d1dd48d5b5392

test:
  secret_key_base: bfe9afee638d923c04fb55cae5b9c1cf16c29bbe52f3424720aee3af9f9c3905df05ca7de771ec0b594161ede648eb9beb4e5668f34fcc2c4dc92eb346a0d98c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
